packageExtensions:
  "@lerna/github-client@*":
    peerDependencies:
      "@octokit/core": ">=3"
  "@lerna/publish@*":
    peerDependencies:
      "@octokit/core": ">=3"
  "@lerna/version@*":
    peerDependencies:
      "@octokit/core": ">=3"
  "@octokit/rest@*":
    peerDependencies:
      "@octokit/core": ">=3"
  lerna@*:
    peerDependencies:
      "@octokit/core": ">=3"

yarnPath: .yarn/releases/yarn-sources.cjs
