yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@octokit/rest@*":
    peerDependencies:
      "@octokit/core": ">=3"
  "@lerna/github-client@*":
    peerDependencies:
      "@octokit/core": ">=3"
  "@lerna/version@*":
    peerDependencies:
      "@octokit/core": ">=3"
  "@lerna/publish@*":
    peerDependencies:
      "@octokit/core": ">=3"
  lerna@*:
    peerDependencies:
      "@octokit/core": ">=3"
